---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : http://blog.hanfeisun.info

posts:
  permalink: '/:year/:month/:filename'
  summary_lines: 10
  latest: 10

pages:
  permalink: 'pretty'